### ISSUE TITLE
Goal - Force Stronger Passwords

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/Awakens-Latest#1]
Goal:
Force strong passwords by default.

Reason:
This should combat brute forcing and make it far more difficult to steal a users account.

Suggestion:
User's should be required to create a password with 1 Capital Letter, 1 Lowercase Letter, 1 Number
Password must be at least 8 Characters long

**Comment by DayDun** [comment]
It should be checked on the client if the password is secure, we could use some library.
