### ISSUE TITLE
Goal - Topic Names/Dates

### ISSUE THREAD

**Issue by FroggMaster** [FroggMaster/Awakens-Latest#2]
Goal:
When a user set's the topic, their name and the date/time they set the topic is temporarily saved to the database until the topic is changed, at which time this information is overwritten.

Reason:
This is mostly just for fun, it's fun knowing who set a topic and how long it's been there.

Suggestion:
Command "/get topicinfo" 
Outputs topic, name of who set topic and date/time when topic was set.

**Comment by DayDun** [comment]
Maybe create a log file on the server? Maybe a bot that logs everything?

**Comment by michael-elbert** [comment]
User is already passed, it wouldn't be hard to add it to the database at all. The hard part would be reconfiguring the localstorage in the client to save the user AND information

**Comment by FroggMaster** [comment]
This was once in the previous code. Look back on my github.
Something RandomGuy committed.
